name: Build Docker with selected version

on:
  workflow_dispatch:
    inputs:
      scilpy_commit:
        description: Dmriqcpy commit id
        required: true

jobs:
  Build_Docker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - name: Change DMRIQCPY version
        run: sed -i '/ENV DMRIQCPY_VERSION=/c\ENV DMRIQCPY_VERSION=${{ github.event.inputs.dmriqcpy_commit }}' Dockerfile
      - uses: mr-smithers-excellent/docker-build-push@v3.1
        name: Docker Build & Push
        with:
          image: scilus/dmriqcpy
          tag: dev
          dockerfile: Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
